### PR TITLE
Added Bereket's card

### PR DESCRIPTION
**Pull request by bereketsemagn**

### CODE REVIEW

**Comment by RocktimSaikia** [comment]
I recently made some new changes to the project which is causing this conflict . You can pull the latest changes from this original master branch and push it again after resolving the conflict. If you have any question or need any help ,You can ask me right here.

**Comment by bereketsemagn** [comment]
Mind explaining more @RocktimSaikia?

**Comment by RocktimSaikia** [comment]
You forked this repo before the new changes that I've made a few minutes ago. That means your forked version is behind this original master branch by few new commits. So since your forked version is not updated with the latest changes, it's causing this minor conflict. And what you meed to do to resolve this `merge conflict` is that you have pull the latest changes from the original `master` branch and update your branch with those changes then commit and push them again. This may sound a bit confusing if you have never dealt with git merge conflicts before which is pretty common for new developers. Do you have any experience dealing with merge conflicts ?

**Comment by bereketsemagn** [comment]
No @RocktimSaikia

**Comment by RocktimSaikia** [comment]
I can resolve the conflict for you but that would ruin the fun of `Hacktoberfest `. You can try to resolve the conflict by yourself by doing some research on the net or just take a look at this article on how to resolve a conflict.
https://dzone.com/articles/how-to-resolve-github-merge-conflicts

There is two ways mentioned in this article to do this but try learn the second way which is 
> "Conflicts From Pulling Remote Changes to a Local Repository"

**Comment by RocktimSaikia** [comment]
closing cause of inactivity

**Pull request closed without merging**
