### PR TITLE
Divanshi's card

### PR DESCRIPTION
**Pull request by divanshi15**

### CODE REVIEW

**Comment by RocktimSaikia** [comment]
Hi @divanshi15  . You can fix the style errors by running `npm run lint:fix` in  your project directory.If you need any help .I'm here :)

**Comment by divanshi15** [comment]
i dont know what to do can you ellaborate more please.

**Comment by RocktimSaikia** [comment]
@divanshi15 Sure . Right now your code has some minor style errors like `double quote` , `syntax errors ` which might be hard to notice if the codebase is large. So i have already set up some `linting scripts` that you can run on your version of the project. 
Follow these steps :
1) Go to your project on your local machine and check which branch you are on .In your case `master or myCard` . 

2) If you are on `master branch` then run 
```
git checkout myCard
``` 
to go to your `myCard` branch.

3) Now run 
```
npm install
```
to install all the packages then
```
npm run lint
``` 
This will show you any error that in the codebase . 

4)And then just run 
```
npm run lint:fix
```
This will fix all style related errors. And you are done.Now just push that branch by running 
```
git push origin myCard
```
 That's all.

**Comment by RocktimSaikia** [comment]
@divanshi15 Hi , I resolved your errors . Thanks for contributing :)

**Pull request closed without merging**
