### PR TITLE
Adding Profile Picture to card

### LINKED ISSUE #82: Fetch github profile and add them to the card .
Right now we have a basic work flow going on .The contributors provide their basic info and we just simply loop through the data and make a card out of it . Along with additional details new contributors also provide their` github username` in the data object.Currently we just use the user_name to add a link to their github profile.But it would be nice if we could also show their `github profile picture` in the card.

This is our current data model which is an `array `of objects :
```
{
name: '',
country: ",
role: '',
tech_stack: ",
github_username: "",
twitter_username: ""
}
```

So what we have to do is to loop through the array of data and fetch the github profile picture using the provided property `github_username` . In a way it is just a fairly simple fetching requirement.

If anyone wants to work on it ,you are more then welcome.
If any help needed i'm here !

Helpful links : 
[https://developer.github.com/v3/users/](https://developer.github.com/v3/users/)

### PR DESCRIPTION
**Pull request by unsuitable001**
Fetching github profile picture using github API & adding them to card.
Fixes #82

### CODE REVIEW

**Comment by RocktimSaikia** [comment]
@unsuitable001 Please follow this :point_right:  [STYLE GUIDELINE](https://github.com/RocktimSaikia/Contribute-101/blob/master/contributors-guide.md) to pass the CI tests

**Comment by unsuitable001** [comment]
@RocktimSaikia Done!

**Comment by RocktimSaikia** [comment]
@unsuitable001 Hi . I just tested your code and currently it does not seems to work.Because the `List` is being rendered before it gets updated with the fetched profile pictures.Are you familiar with `promises `and `callbacks` . You need to do something like this 
```
(the github profile are being fetched )
   and when done; update the `List `with the fetched data.
   then render the list to the view
```
Right now the `List `is being rendered before the fetching is done.thats why we are not seeing the images.You need to work with promises to work around with this issue. There are tons of articles on promises you can check online.

**Comment by unsuitable001** [comment]
@RocktimSaikia I think it has another issue. I was console logging and the response of the API was limit exceeded. The current Rate Limit is 60/hr. (I utilized most of it in other purpose)

**Comment by unsuitable001** [comment]
Delete most of the list (except 4-5 people), while testing.. :smiley:

**Comment by RocktimSaikia** [comment]
#100 fixed

**Pull request closed without merging**
