### PR TITLE
Readme Updated

### PR DESCRIPTION
**Pull request by IC1101Virgo**
Here are the changes to readme which I have made. Review this and tell me the changes that are required or any edits. I have named this as Name-Card by mistake. Sorry!

### CODE REVIEW

**Comment by RocktimSaikia** [comment]
@IC1101Virgo Epic 🚀. Merging... 
Also do keep an eye for more issues.

**Comment by IC1101Virgo** [comment]
@RocktimSaikia Thank you! 
Yes I will  :)  😀

**Comment by RocktimSaikia** [comment]
@IC1101Virgo If you want to work on something more on the technical side then you can work on this issue #262 too. A fairly simple hook implementation. If you have not worked with hooks before then it will be a new learning experience too.
> To get all sorts help and quick responses you can join my [discord server](https://discord.gg/HAZEng) too,I am active there most of the time :unicorn:

**Comment by IC1101Virgo** [comment]
@RocktimSaikia I am willing to learn ! I'll take this up
:3

**Pull request merged**
