### PR TITLE
Upasana's Card

### PR DESCRIPTION
**Pull request by upasanadeka**
Added my details in a Card.

### CODE REVIEW

**Comment by upasanadeka** [comment]
I am not able to understand the conflict. Kindly help!
@RocktimSaikia

**Comment by RocktimSaikia** [comment]
@upasanadeka Hi thanks for contributing :) but seems like there are some conflicts that needs to be resolved .I will resolve them soon enough but in the meantime If you want to resolve them , you can do that too :)

**Comment by upasanadeka** [comment]
> @upasanadeka Hi thanks for contributing :) but seems like there are some conflicts that needs to be resolved .I will resolve them soon enough but in the meantime If you want to resolve them , you can do that too :)

I'd like to try to resolve them, but I don't understand the conflict. Can you let me know the steps for the same?

**Comment by RocktimSaikia** [comment]
@upasanadeka Hi :) Looks like previous commits by other developers left some redundant div tags.It also conflicted with the template card. It may me hard for someone new to this repo to get their head around as the index.ejs file is becoming quite large.I will resolve the conflicts for this time. 
As the codebase becoming quite messy i'm making some major changes to the repo.I will open some issues.You can work on them if you want :)

**Comment by upasanadeka** [comment]
Sure. Thanks!

**Comment by RocktimSaikia** [comment]
@upasanadeka I just did major update on the whole project from data models to ui design. So previous methods of adding card wont work. You can see the new updated README.md with steps explained how to contribute to this new project structure. :) Thanks

**Pull request closed without merging**
