### PR TITLE
Responsive done Fixed#255

### PR DESCRIPTION
**Pull request by anushri20**

### CODE REVIEW

**Comment by RocktimSaikia** [comment]
@anushri20 I don't think it made site responsive. Please test properly before submitting.

**Comment by anushri20** [comment]
@RocktimSaikia Hi, I have added the following code in style.css and it is working correctly on mutliple devices.
I don't know why it's not working on your device.

image


image

**Comment by RocktimSaikia** [comment]
@anushri20  I am guessing you are using chrome . Try testing in any Firefox variant .  The site breaks in both Firefox and Firefox dev.

**Comment by anushri20** [comment]
@RocktimSaikia I am so sorry about that, I'll make the changes asap. Thank you.

**Comment by RocktimSaikia** [comment]
@anushri20 It's totally fine .There is nothing to be sorry about that.

**Comment by RocktimSaikia** [comment]
Are you not using any code formatter ? There isn't the necessary spaces between some css rules. These things are generally auto formatted when there is formatter like `prettier` installed. Also if you look at the docs I highly suggest everyone contributing to check for style errors by running `npm run lint`. 
Anyway other than that looks good to me 🎉. Still there are some minor things that can be improved in your pr ,so I will make the rest of the changes to your pr and push it when it's done.

**Comment by anushri20** [comment]
@RocktimSaikia Yaah i guess there are some issues with prettier in my system, I will look upon it. Sorry about that and Thank You !!

**Comment by RocktimSaikia** [comment]
@anushri20  I see. Anyway I pushed the changes along with updated code :+1:  Keep an eye for new issues and mention me for any further help.

**Comment by anushri20** [comment]
@RocktimSaikia Yeah sure, Thank you !!

**Pull request closed without merging**
